# Generated by Django 5.2.1 on 2025-07-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opponent_goals',
            field=models.PositiveIntegerField(default=0, verbose_name='Gols do Adversário'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_goals',
            field=models.PositiveIntegerField(default=0, verbose_name='Gols do Time'),
        ),
    ]
